### ISSUE TITLE
Add a proper README

### ISSUE THREAD

**Issue by thecashewtrader** [GibreelAbdullah/Hadith-Hub#18]
Good templates I've found are:
- [CFPB Open Source Project Template Instructions](https://github.com/cfpb/open-source-project-template)
- [Awesome README](https://github.com/matiassingers/awesome-readme)

**Comment by GibreelAbdullah** [comment]
Closed with commit - https://github.com/GibreelAbdullah/Hadith-Hub/commit/02fc91b892e3bb81736ca93ced0700408c6f6e0a
