### ISSUE TITLE
Multipart hadith links don't work

### ISSUE THREAD

**Issue by G00DF3LLA** [GibreelAbdullah/Hadith-Hub#28]
If I visit a multipart hadith such as [Tirmidhi 2743](https://www.hadithhub.com/tirmidhi:2743), the .2 or .3 parts don't work such as [Tirmidhi 2743.2](http://www.hadithhub.com/tirmidhi:2743.2).

Likely related, for the affected hadith it shows "Book 0, Hadith 0" and does not show any gradings.

Other services use b, c, d instead of .2, .3, .4.

**Comment by GibreelAbdullah** [comment]
I am currently working on redesigning the database to add more features. I will keep this bug in mind.

**Comment by GibreelAbdullah** [comment]
Closed. The links will now be of the parent hadith.
