### ISSUE TITLE
Can you add a max-width for hadith for ultrawide monitors?

### ISSUE THREAD

**Issue by ghost** [GibreelAbdullah/Hadith-Hub#32]
The page is too stretched and hard to read when viewing on monitors that are larger than the standard size. 3440x1440p is what I use and the content is too wide. It would be better if you add a container with a max-width of say 1300px. If you want I can look into this for you.

**Comment by GibreelAbdullah** [comment]
InShaAllah will fix this tomorrow.

**Comment by GibreelAbdullah** [comment]
Fixed with [Fixed max width for ultra wide monitors.](https://github.com/GibreelAbdullah/Hadith-Hub/commit/a5aaab6dfb76a4b9d6b40cececf3c363a59e8eea)

Jazakallahu Khairan for bringing this to my notice. Kindly let me know if this looks good.

**Comment by ghost** [comment]
> Fixed with [Fixed max width for ultra wide monitors.](https://github.com/GibreelAbdullah/Hadith-Hub/commit/a5aaab6dfb76a4b9d6b40cececf3c363a59e8eea)
> 
> Jazakallahu Khairan for bringing this to my notice. Kindly let me know if this looks good.

Wa iyyaka. Much better JazakAllah Khair
