### ISSUE TITLE
Fix grading source showing as undefined

### ISSUE THREAD

**Issue by ghost** [GibreelAbdullah/Hadith-Hub#33]
![image](https://github.com/GibreelAbdullah/Hadith-Hub/assets/55749172/4f13a9a8-f4b8-4688-a4f1-6106019aec5e)

I am unsure where the sources for Al-Albani's checking is coming from. Would be good if this can be fixed.

**Comment by GibreelAbdullah** [comment]
I had documented everything in one file but accidentally deleted that file without checking it on github. Will have document again.
All the references are from https://github.com/GibreelAbdullah/hadith-api/blob/1/References.md

**Comment by GibreelAbdullah** [comment]
Fixed
