### ISSUE TITLE
"Copied" text bug

### ISSUE THREAD

**Issue by thecashewtrader** [GibreelAbdullah/Hadith-Hub#6]
Currently, on clicking "Copy Permalink", the text for *all* buttons changes to "Copied".

Reproduction:
- Visit https://hadithhub.com/bukhari:1
- Click on "Copy Permalink"
- Both buttons' text changes

I looked into the code and SvelteKit docs, but can't seem to find the root cause.

**Comment by GibreelAbdullah** [comment]
Fixed in [69c6991](https://github.com/GibreelAbdullah/Hadith-Hub/commit/69c6991e89410509d03c4277620ddd871f5fa1c6)
