### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by thecashewtrader** [GibreelAbdullah/Hadith-Hub#9]
Helpful resource: [Choose A License](https://choosealicense.com/)

**Comment by GibreelAbdullah** [comment]
I'm thinking of [GNU GPLv3](https://choosealicense.com/licenses/gpl-3.0/) license. What do you think?
The data  (hadith-api) is [unlicense license](https://github.com/GibreelAbdullah/hadith-api/blob/3/LICENSE) since the parent repo is using the same.

**Comment by thecashewtrader** [comment]
GPLv3 is good enough but [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) would be even better.

**Comment by GibreelAbdullah** [comment]
Added AGPLv3. Thanks. Closing
